### ISSUE TITLE
Vector Compose Algorithm?

### ISSUE THREAD

**Issue by doganulus** [johnyf/dd#17]
I wonder which algorithm used for the implementation of vector compose. Are you aware of any result on time and space complexities of this operation?

**Comment by johnyf** [comment]
Vectorized composition is simultaneous substitution of multiple variables with arbitrary expressions, the latter as BDD nodes (so `LET x = y, y = x IN x /\ ~ y` should yield `y /\ ~ x`). Currently, it is available only [in `dd.cudd`](https://github.com/johnyf/dd/blob/c535dee7a2e0d4c7312c383855c6239e87afcd37/dd/cudd.pyx#L680), where [`Cudd_bddVectorCompose`](https://github.com/johnyf/cudd/blob/80c9396b7efcb24c33868aeffb89a557af0dc356/cudd/cudd/cuddCompose.c#L787) is called from [here](https://github.com/johnyf/dd/blob/c535dee7a2e0d4c7312c383855c6239e87afcd37/dd/cudd.pyx#L633).

`dd.bdd` [includes `compose`](https://github.com/johnyf/dd/blob/c535dee7a2e0d4c7312c383855c6239e87afcd37/dd/bdd.py#L396), but for one variable at a time. There is a todo item to offer vectorized composition there. It is already implemented, in the sense that it is essentially the same algorithm with `rename`, `cofactor`, and `evaluate`, where one can pass multiple variables or constants and they are replaced in one pass, down as the BDD graph is being "rezipped".

A naive first `dev` implementation wasn't simultaneous composition, so it was omitted (more details in #12 https://github.com/johnyf/dd/pull/11#issuecomment-219302353). Because of `compose` being essentially the same algorithm with `rename` etc., I would like to consolidate these methods into one, as described in #12. The only real difference between them is user input, and that can still be available as methods with different signatures that call the same method implementing the algorithm.

There is a good chance that a method called `BDD.replace` will be preferred, for the reasons described [here](https://github.com/johnyf/dd/issues/12#issuecomment-245211788). The name `replace` has been used in the first-order interface (i.e., integers and arithmetic) to BDDs in [`omega.symbolic.fol`](https://github.com/johnyf/omega/blob/v0.0.9/omega/symbolic/fol.py#L102) (which I also recommend using -- just beware it may be a little unstable in the near future, because it has been freshly minted).

As far as the complexity of compose is concerned, in the worst case the running time can be exponentially large (even if an ideal memory was used for memoizing intermediate results), because it solves SAT (pick `TRUE` and `FALSE` as replacement BDDs for all the variables).

The best reference is [Bryant's original paper](http://dx.doi.org/10.1109/TC.1986.1676819), which is highly readable, to the point, and I highly recommend it (also, the original PDF). *Single variable* composition is covered in Sec.IV-E, p.685, where the complexity is shown to be `O( NumberOfNodes(G1)^2 NumberOfNodes(G2))`. The [updated version](https://www.cs.cmu.edu/~bryant/pubdir/ieeetc86.pdf) comments in footnote 8, p.16 that this bound is tight.

For use cases where some variable is replaced by some given BDD, improvements rely on what that BDD is. This is what `rename` exploits, for variables with neighboring levels, to reduce the complexity. The complexity of `rename` and `cofactor` (which are special cases of `compose`) is discussed in [Baier and Katoen](http://dl.acm.org/citation.cfm?id=1373322), pp.416--421. It is a good overview, though I do not recommend it for learning those particular algorithms, because they are written in a complicated and messy way. Quoting p.416: "... there is no linear-time algorithm that realizes the rename operator for arbitrary variable orderings".

The way that these functions are implemented in Python, the space complexity relates to the number of intermediate results, because they are simply [memoized in a `dict`](https://github.com/johnyf/dd/blob/master/dd/bdd.py#L433). This is intentional, i.e., I have written a simple and (hopefully) readable implementation. [Premature optimization is the root of all evil](http://dx.doi.org/10.1145/356635.356640), i.e., `dd.bdd` has value for development, prototyping, debugging, easy deployment, and education. Not for industrial use -- that is served by `dd.cudd`.

It so happens that `dd.bdd` actually works well in practice, but I would be reluctant to sacrifice readability and simplicity for performance. Instead, I would prefer to write, say, another, optimized, BDD implementation in a separate Python module, and have it be used if needed (for example, see debug and optimized versions of functions in [`ply`](https://github.com/dabeaz/ply)). The dual implementation approach serves also for cross-testing code (the simple implementation can be used as a reference, because it is less likely to contain errors).
