### ISSUE TITLE
Subsumption check "bdd1 \subseteq bdd2"

### ISSUE THREAD

**Issue by 5nizza** [johnyf/dd#2]
hi! this is a question not an issue:

is there a way to check one bdd node is subsumed by another?
Why: to check in the fixpoint computation if the initial state is in the winning region.

In pure quantification and boolean operators this can be implemented as: 

    def is_subset_of(x,y):
        return (forall{vars} (x=>y)) == BDD.TRUE

But may be there is a more efficient way in `dd` for doing this?
E.g., CUDD has `Cudd_bddLeq` which seems to be the subsumption check.

**Comment by johnyf** [comment]
The subset relation can be checked with [implication](https://github.com/johnyf/dd/blob/v0.1.3/dd/bdd.py#L986). With any of [`dd.bdd.BDD`](https://github.com/johnyf/dd/blob/v0.1.3/dd/bdd.py#L54), [`dd.autoref.BDD`](https://github.com/johnyf/dd/blob/v0.1.3/dd/autoref.py#L8), [`dd.cudd.BDD`](https://github.com/johnyf/dd/blob/v0.1.3/dd/cudd.pyx#L152) as `_bdd`:

```python
bdd = _bdd.BDD()
for var in ['x', 'y']:
    bdd.add_var(var)
x = bdd.var('x')
y = bdd.var('y')

u = bdd.apply('and', x, y)
v = bdd.apply('or', x, y)
subset = bdd.apply('implies', u, v)
assert subset == bdd.True, subset
```

When using `dd.autoref.BDD` or `dd.cudd.BDD`, one can also do:

```python
x = bdd.var('x')
y = bdd.var('y')

u = x & y
v = x | y
subset = ~u | v
```

because the nodes are represented by [`autoref.Function`](https://github.com/johnyf/dd/blob/v0.1.3/dd/autoref.py#L187) and [`cudd.Function`](https://github.com/johnyf/dd/blob/v0.1.3/dd/cudd.pyx#L713) objects, instead of bare integers, as in `dd.bdd`. The interface exposed by `autoref` and `cudd` is (almost) the same, in order to enable writing code once, then running it with:

- `dd.autoref`, if only Python packages are installed
- `dd.cudd`, if the CUDD bindings have been compiled, for heavier use cases.

Note that both `'and', 'or', 'implies'` and `'&', '|', '->'` can be used. The implication should produce the same result as [`Cudd_bddLeq`](https://github.com/blambeau/cudd/blob/1d0da4f64a0be297207906953d275804b24a92f3/cudd/cuddBddIte.c#L673). However, for now, the result of `apply` is obtained with `ite` (if-then-else), so it computes the implication (in [`cudd.pyx`](https://github.com/johnyf/dd/blob/v0.1.3/dd/cudd.pyx#L395) too), therefore it is expected to be less efficient than the implementation of `Cudd_bddLeq`. Nonetheless, quantification is not involved, so the difference in performance is likely to be negligible in most use cases.

An example check for initial conditions for generalized Streett(1) games can be found in [`omega.games.gr1`](https://github.com/johnyf/omega/blob/v0.0.2/omega/games/gr1.py#L185). Note though, that the example involves mixed quantification. The discussion above refers to universal quantification for all variables (hence the subset check).

You mention "initial state", instead of "initial states". If there is a single initial state, then one can directly evaluate the winning set at the initial state, using [`dd.bdd.BDD.evaluate`](https://github.com/johnyf/dd/blob/v0.1.3/dd/bdd.py#L246) or [`dd.cudd.BDD.cofactor`](https://github.com/johnyf/dd/blob/v0.1.3/dd/cudd.pyx#L360).

**Comment by 5nizza** [comment]
wow, thank you for detailed answer and links to the omega example!
