### ISSUE TITLE
interpretation of BDD graph plot

### ISSUE THREAD

**Issue by numshub** [johnyf/dd#29]
When plotting a simple bdd via dump, I get an inconsistent graph.
Expression: `"x /\ y /\ ~z"`
Output graph is attached.
`sat_iter` returns the right decision set `dict(x=True, y=True, z=False}`, but the graph (attached) looks wrong to me.

[out.pdf](https://github.com/johnyf/dd/files/870387/out.pdf)

Code to reproduce:

```python
>> from dd import autoref as _bdd
>> bdd = _bdd.BDD()
>> [bdd.add_var(k) for k in "xyz"]
>> u = bdd.add_expr("x /\ y /\ ~z")
>> bdd.collect_garbage()
>> bdd.dump("out.pdf")
```

**Comment by johnyf** [comment]
The graph of the BDD `x /\ y /\ ~ z` attached to the OP looks correct to me. What may seem unfamiliar compared to several presentations of BDD concepts is that it uses complemented edges. Solid edges are for `var = TRUE`, dashed for `var = FALSE`, where `var` is the variable identifier that labels the node. Only dashed edges can be complemented, and in this BDD there is a single complemented edge: `<< 5, 1 >>` where the integers are the indices of the nodes (`z-5` and `True-1`).

A more complete description of the plots can be found [here](https://github.com/johnyf/dd/blob/e5aa95bf118db18699d4f0c297e0f9dfc68243a7/doc.md#plotting) in the documentation.

Complement arcs are discussed within the first 5 pages of [Fabio Somenzi's "Binary decision diagrams"](http://www.ecs.umass.edu/ece/labs/vlsicad/ece667/reading/somenzi99bdd.pdf), and an excellent reference is ["Efficient implementation of a BDD package" by Brace, Rudell and Bryant](https://www21.in.tum.de/~lammich/2015_SS_Seminar_SAT/resources/BraceRudellBryantBDDPackage.pdf).

**Comment by johnyf** [comment]
Also, I would suggest using the newly introduced method `BDD.pick_iter` instead of `BDD.sat_iter`, because the latter was deprecated a few days ago, and will be removed in the future.

**Comment by johnyf** [comment]
@numshub has the question been answered? Can the issue be closed?

**Comment by numshub** [comment]
Thank you for the clarification and the excellent links. I am not actually familiar with this convention for ROBDD. If I look at the example above (x&y&~z) I do not see how a dashed line (false) out of x or y can point to True. I would have expected these edges to be complemented and not the one starting from z. In my approach the solid edge out of z should be complemented, but this is not possible in order to preserve canonicity. I think the graph can be obtained by transforming the nodes in order to enforce the convention, but I did not try yet. For the moment I will assume that the graph is right and I put this aside for a later time when I have some more time to invest. Meanwhile thank you for the fine job on this library and for your support.

**Comment by johnyf** [comment]
Thank you for the response, I see now what I should have mentioned above, but didn't. The missing piece is what polarity the edge `u` has (despite being outside the manager, I call it "edge" because it serves as an edge whose source node is "the user"). The plot shows the graph reachable from the node referenced by `u`, but whether `u` itself is a normal or a complemented edge is not part of the plot.

All nodes within a manager that uses complemented edges are "rectified", in that they represent the result of applying the rules about complemented edges for obtaining a canonical form (those described in Brace-Rudell-Bryant cited [above](https://github.com/johnyf/dd/issues/29#issuecomment-289242583)). So, a single node in the manager can be used to represent both the Boolean function that we read below it, as well as its negation.

In `dd.bdd.BDD`, nodes are positive integers, and edges are signed integers. Solid edges are always positive integers, dashed are positive (not complemented) or negative (complemented) integers. The reference that a user gets out of a manager (`u` in our case) may, or may not be complemented. Therefore, it is an edge (because it must accommodate for referring, for each Boolean function, to both the function itself as well as its negation, but only one of them is represented by a node in a manager that uses complemented edges).

For `x /\ y /\ ~ z`, the node that results from the OP satisfies:

```python
assert u.node == -7
```

So `u` refers to the *negation* of node 7. I showed above the low-level way of looking at `u`, in order to connect with my previous remarks. Since we are using `autoref` (high level interface), it suffices to look at the attribute that tells whether `u` is complemented:

```python
assert u.negated is True
```

Returning to the plot, the Boolean function it represents is:

```tla
\/ ~ x
\/ ~ y
\/ z

\equiv

IF x THEN
    IF y THEN
        (IF z THEN TRUE ELSE ~ TRUE)
    ELSE
        TRUE
ELSE
    TRUE
```

The `dd.autoref.Function` reference we have is a negated edge, so we need to negate the above to get the Boolean function that *we* are referring to via `u`:

```
~ ( ~ x \/ ~ y \/ z ) \equiv
x /\ y /\ ~ z
```

The nodes in the graph are what in CUDD are called "regular" versions, what you get from applying the macro [`Cudd_Regular`](https://github.com/johnyf/cudd/blob/1bb1ed3de3b00c4c82577027c08e79ae9e9f4a87/cudd/cudd/cudd.h#L321). Keeping track of complementation status and propagating the complement bit upwards (until it "pops out" of the manager to `u`, depending on the Boolean function) is a sensitive point of implementing recursive BDD operations, and a common source of errors.

Note that the above results because I chose in `dd.bdd`  to complement "else" arcs, as CUDD does. Choosing "then" arcs would lead to a symmetric collection of represented Boolean functions as canonical (I believe Sylvan makes that choice).

Also:

```python
>>> bdd.to_expr(u)
'(! ite(x, ite(y, z, True), True))'

>>> v = ~ u
>>> bdd.to_expr(v)
'ite(x, ite(y, z, True), True)'
```

Perhaps I should clarify somewhere in the documentation, and the docstring of `BDD.dump`, that the plot shows the canonical forms, not the polarity of `u`, which the user gives as input argument (one reason is that `u` is external to the manager).

**Comment by numshub** [comment]
Now it totally makes sense. I was looking in the right direction but your explanation made everything clear. As pointed out, it also explains the design choice of keeping u external to the manager (which looked awkward to me at the beginning). Thanks again.
